### ISSUE TITLE
Eurosport 2 missing

### ISSUE THREAD

**Issue by heinci** [movieshark/DigiOnline#1]
Eurosport 2 is missing from the channel list.

**Comment by MrDini123** [comment]
Sadly no repro on my end it works fine: [image](https://i.imgur.com/YGvEJtb.gif)

However the addon builds its channel list dynamically and for that I use the channel list provided by the website. In case if the channel has no data-id number it means the currently streamed content is not playable online therefore I won't even display the channels without that tag. See the code here:

https://github.com/movieshark/DigiOnline/blob/bde5af5b091baa432fe02aebf07cd6f3ecc526ca/plugin.video.dinionline/default.py#L149-L158

Please check if you can see the channel now.

**Comment by heinci** [comment]
Yesterday it was missing, but I checked it again and I can see it now.
Thank you for your quick reply and this amazing add-on, I really appreciate your work.

**Comment by MrDini123** [comment]
Alright, glad to hear it's there now. Thanks for the quick feedback!
